[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = false

[[headers]]
  for = "/privacy.html"
    [headers.values]
    Content-Type = "text/html"
    X-Content-Type-Options = "nosniff"
