[build]
command = "npm run build"
publish = "dist"

# Don't redirect privacy.html to index.html
[[headers]]
  for = "/privacy.html"
  [headers.values]
    Content-Type = "text/html"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Path = "!/privacy.html"}

[build.environment]
  NODE_VERSION = "18"
